name: Go CI

on:
  push:
<<<<<<< HEAD
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
=======
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
>>>>>>> master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22" # adjust to your Go version

      # Step 3: Install dependencies (optional if using modules)
      - name: Get dependencies
        run: go mod tidy

      # Step 4: Run build
      - name: Build
        run: go build -v ./...

      # Step 5: Run tests
      - name: Test
        run: go test -v ./...
